config/routes.rb
Rails.application.routes.draw do





  # DEVISE setup
  devise_for :users

  ## FROM PRIMO Link
  get "/from_primo" => "from_primo#show"

  ## LOGIN VIA PASSPORT YORK
  get "/ppy_login" => "ppy_login#show"

  get "/home" => "home#show"

  ## LOAD FEES from ALMA
  get "alma/load_fees" => "alma/load_fees#index", as: :load_alma_fees

  ## REDIRECTOR to payment broker
  get "redirecting/to_payment_broker" => "redirectors/to_payment_broker#show", as: :redirect_to_payment_broker

  ## REDIRECTOR to alma fine payment
  get "redirecting/to_alma_fines" => "redirectors/to_alma_fines#show", as: :redirect_to_alma_fines

  ## POSTBACK From YPB
  resource :ypb_postback, only: :create, controller: "ypb_postback"

  ## PAYMENTS ##

  ## processing, creating transactions and records
  resources :process_payments, only: [:new, :create]

  ## details for completed transactions
  resources :transactions, only: [:index, :show]

  ## HOME ##
  root 'from_primo#show'

  ## REPORTS ##
  get "/reports" => "reports#index", as: :reports
  get "/reports/transaction/:id" => "reports/transactions#show", as: :report_transaction
  get "/reports/transaction/:id/logs" => "reports/transaction_logs#show", as: :report_transaction_log

  ## DUMMY ALMA API ##
  unless Rails.env.production?
    get "alma/dummy_api/:user_id/fees/" => "alma/dummy_fees_api#show", as: :alma_dummy_api_get_fees
    post "alma/dummy_api/:user_id/fees/:fee_id" => "alma/dummy_fees_api#update", as: :alma_dummy_api_fees
  end

end

app/helpers/layout_helper.rb
module LayoutHelper
  def page_title(title="Untitled")
    content_for(:page_title) { h title.to_s }
  end

  def page_header(header, page_title: false)
    content_for(:page_header) { h header.to_s }
    page_title header if page_title == true

  end

  def page_description(description)
      content_for(:page_description) { h description.to_s }
  end

end

app/views/layouts/shared/top_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary static-top">
    <div class="container">
      <a class="navbar-brand" href="<%= Settings.app.url %>">
        <%= Settings.app.name %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <% if current_user != nil %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= home_url %>">Fines+fees
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="<%= transactions_path %>">Payment History
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <% if current_user.admin? %>
            <li  class="nav-item active">
              <a class="nav-link" href="<%= reports_path %>">Reports</a>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>