config/routes.rb
Rails.application.routes.draw do





  # DEVISE setup
  devise_for :users

  ## FROM PRIMO Link
  get "/from_primo" => "from_primo#show"

  ## LOGIN VIA PASSPORT YORK
  get "/ppy_login" => "ppy_login#show"

  get "/home" => "home#show"

  ## LOAD FEES from ALMA
  get "alma/load_fees" => "alma/load_fees#index", as: :load_alma_fees

  ## REDIRECTOR to payment broker
  get "redirecting/to_payment_broker" => "redirectors/to_payment_broker#show", as: :redirect_to_payment_broker

  ## REDIRECTOR to alma fine payment
  get "redirecting/to_alma_fines" => "redirectors/to_alma_fines#show", as: :redirect_to_alma_fines

  ## POSTBACK From YPB
  resource :ypb_postback, only: :create, controller: "ypb_postback"

  ## PAYMENTS ##

  ## processing, creating transactions and records
  resources :process_payments, only: [:new, :create]

  ## details for completed transactions
  resources :transactions, only: [:index, :show]

  ## HOME ##
  root 'from_primo#show'

  ## REPORTS ##
  get "/reports" => "reports#index", as: :reports
  get "/reports/transaction/:id" => "reports/transactions#show", as: :report_transaction
  get "/reports/transaction/:id/logs" => "reports/transaction_logs#show", as: :report_transaction_log

  ## DUMMY ALMA API ##
  unless Rails.env.production?
    get "alma/dummy_api/:user_id/fees/" => "alma/dummy_fees_api#show", as: :alma_dummy_api_get_fees
    post "alma/dummy_api/:user_id/fees/:fee_id" => "alma/dummy_fees_api#update", as: :alma_dummy_api_fees
  end

end

app/controllers/process_payments_controller.rb
class ProcessPaymentsController < AuthenticatedController
  def new
    if params[:osgoode]
      @fees = current_user.alma_fees.osgoode_fees
      @which = "Osgoode"
    else
      @fees = current_user.alma_fees.other_fees
      @which = "York University Libraries"
    end

    @records = []
    @fees.each do |fee|
      if ! fee.payment_pending?
        @records << PaymentRecord.new(user: current_user, fee: fee, amount: fee.balance)
      end
    end
  end


  def create
    @records = []

    record_params[:payment_record].keys.each do |key|
      amount = record_params[:payment_record][key]["amount"]
      if ! amount.blank?
        fee = Alma::Fee.active.find_by_id key
        if fee
          @records << PaymentRecord.new(user: current_user, fee_id: key.to_i, amount: fee.balance )
        end
      end
    end


    if @records.size > 0

      @transaction = PaymentTransaction.create! status: PaymentTransaction::STATUS_NEW,
                                                yorku_id: current_user.yorku_id,
                                                user: current_user

      TLOG.log_transaction_step step: TransactionLog::YPB_START,
                  yorku_id: current_user.yorku_id, transaction_id: @transaction.id,
                  message: "Created new transaction. Status: #{@transaction.status}"

      total_amount = 0
      library_id = nil
      @records.each do |record|
        record.payment_transaction = @transaction
        total_amount += record.amount
        record.save

        TLOG.log_transaction_step step: TransactionLog::YPB_START,
                    yorku_id: current_user.yorku_id, transaction_id: @transaction.id,
                    message: "Alma Record: #{record.fee.item_barcode rescue 'error'} Amount: #{record.amount}"

        #TLOG.record current_user.yorku_id, "For record: #{record.fee.item_barcode rescue 'error'}"

        # save library id
        library_id = record.fee.owner_id if library_id == nil
      end

      @transaction.update library_id: library_id
      @transaction.update amount: total_amount


      TLOG.log_transaction_step step: TransactionLog::YPB_START,
                  yorku_id: current_user.yorku_id, transaction_id: @transaction.id,
                  message: "Total Amount: #{total_amount}"

      #TLOG.record current_user.yorku_id, "Total Amount: #{total_amount}"


      redirect_to redirect_to_payment_broker_path(transaction_id: @transaction.id)
    else
      redirect_to new_process_payment_path, notice: "Please provide the amount you would like to pay"
    end
  end


  private
  def record_params
    params.require(:records).permit!
  end
end

app/views/process_payments/new.html.erb
<% page_header "Pay Fees - #{@which}", page_title: true %>

<%= simple_form_for :records, url: process_payments_path do |f| %>


  <% @records.each do |record| %>
    <%= f.fields_for "payment_record[#{record.fee_id}]" do |fr| %>

      <div class="row  mb-4">
        <div class="col-12 col-md-6 pb-2">
          <span class="text-muted text-sm">Fee Details -  <%= record.fee.owner_description %></span><br/>
          <%= record.fee.item_title %>
          <div class="xtext-sm text-muted">
            <%= record.fee.fee_description %>
          </div>
        </div>
        <div class="col-5 col-md-3 text-center">
          <span class="text-muted text-sm">Balance</span>
          <div class="h6 px-1 py-2"><%= number_to_currency record.fee.balance %></div>
        </div>

        <div class="col-6 col-md-3">
          <span class="text-muted text-sm">Pay Fee</span><br/>
          <div class="custom-control custom-switch">
            <input type="checkbox" name="records[payment_record[<%= record.fee_id %>]][amount]"
                class="custom-control-input" checked="checked"
              id="records_payment_record_<%= record.fee_id %>__amount">
            <% fr.check_box :amount, class: "custom-control-input" %>
            <label class="custom-control-label cursor-pointer"
                  for="records_payment_record_<%= record.fee_id %>__amount">
              Pay This Fee
            </label>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-12 offset-md-9 col-md-3">
      <%= f.button :submit, "Pay Fees", class: 'btn btn-primary', data: { confirm: "Are you sure?" } %>
    </div>
  </div>

<% end %>