config/routes.rb
Rails.application.routes.draw do





  # DEVISE setup
  devise_for :users

  ## FROM PRIMO Link
  get "/from_primo" => "from_primo#show"

  ## LOGIN VIA PASSPORT YORK
  get "/ppy_login" => "ppy_login#show"

  get "/home" => "home#show"

  ## LOAD FEES from ALMA
  get "alma/load_fees" => "alma/load_fees#index", as: :load_alma_fees

  ## REDIRECTOR to payment broker
  get "redirecting/to_payment_broker" => "redirectors/to_payment_broker#show", as: :redirect_to_payment_broker

  ## REDIRECTOR to alma fine payment
  get "redirecting/to_alma_fines" => "redirectors/to_alma_fines#show", as: :redirect_to_alma_fines

  ## POSTBACK From YPB
  resource :ypb_postback, only: :create, controller: "ypb_postback"

  ## PAYMENTS ##

  ## processing, creating transactions and records
  resources :process_payments, only: [:new, :create]

  ## details for completed transactions
  resources :transactions, only: [:index, :show]

  ## HOME ##
  root 'from_primo#show'

  ## REPORTS ##
  get "/reports" => "reports#index", as: :reports
  get "/reports/transaction/:id" => "reports/transactions#show", as: :report_transaction
  get "/reports/transaction/:id/logs" => "reports/transaction_logs#show", as: :report_transaction_log

  ## DUMMY ALMA API ##
  unless Rails.env.production?
    get "alma/dummy_api/:user_id/fees/" => "alma/dummy_fees_api#show", as: :alma_dummy_api_get_fees
    post "alma/dummy_api/:user_id/fees/:fee_id" => "alma/dummy_fees_api#update", as: :alma_dummy_api_fees
  end

end

app/controllers/home_controller.rb
class HomeController < AuthenticatedController
  before_action :load_alma_fees

  def show
    @fees = Alma::Fee.active.where(yorku_id: current_user.yorku_id)
    @active_fees = @fees.reject { |f| f.payment_pending? }
    @osgoode_fees = @active_fees.reject { |f| f.owner_id != Alma::Fee::OWNER_OSGOODE}
    @other_fees = @active_fees.reject { |f| f.owner_id == Alma::Fee::OWNER_OSGOODE}

    @processing_fees = @fees.reject { |f| ! f.payment_pending? }
  end

  private
  def load_alma_fees
    if session[:alma_fees_loaded] == nil
      redirect_to load_alma_fees_path
    end
  end
end

app/views/home/_fee_listing.html.erb
<div class="row mb-4">
  <div class="col-12 col-md-3 text-center pb-2 ">
      <span class="text-muted text-sm">Date</span><br/>
    <span class="text-muted">
      <%= format_date fee.creation_time %>
    </span>
  <span class="badge badge-pill d-block">  <%= fee.fee_status %></span>
  </div>
  <div class="col-12 col-md-6  pb-2">
    <span class="text-muted text-sm">Item</span><br/>
    <span class="h6 font-weight-light"><%= fee.item_title %></span>
    <div class="xtext-sm text-muted">
      <%= fee.fee_description %>
    </div>
  </div>
  <div class="col-6 col-md-3 text-center">
    <span class="text-muted text-sm">Balance</span><br/>
    <span class="h4"><%= number_to_currency fee.balance %></span>
  </div>

  <!-- <div class="col-6 col-md-2 text-center">
    <span class="text-muted text-sm">Owner</span><br/>
    <% fee.owner_description %>
    <span class="text-sm text-white d-block"><% fee.owner_id %></span>
  </div> -->
</div>

app/views/home/show.html.erb
<% page_header "My Fees", page_title: true %>

<% if @active_fees.size > 0 %>
  <h5  class="text-center text-lg">York University Libraries Fees</h5>
  <% @other_fees.each do |fee| %>
    <%= render "fee_listing", fee: fee %>
  <% end %>

  <p class="text-center">
    <%= link_to "Pay YUL Fees", new_process_payment_path, class: 'btn btn-primary' %>
  </p>

  <% if @osgoode_fees.size > 0 %>
    <hr class="mt-5"/>
    <h5 class="text-center text-lg">Osgoode Hall Law Library Fees</h5>
    <% @osgoode_fees.each do |fee| %>
      <%= render "fee_listing", fee: fee %>
    <% end %>


    <p class="text-center">
      <%= link_to "Pay Osgoode Hall Law Library Fees", new_process_payment_path(osgoode: true), class: 'btn btn-primary' %>
    </p>
  <% end %>


<% else %>
  <p class="text-center">You have no outstanding fees.</p>
<% end %>

<% if @processing_fees.count > 0 %>
  <hr class="mt-5"/>
  <h5 class="mt-5">Processing Fees</h5>
  <% @processing_fees.each do |fee| %>
  <div class="row mb-4">
    <div class="col-12 col-md-2 text-center pb-2 ">
      <span class="text-muted text-sm">Fee Date</span><br/>
      <span class="text-monospace text-sm text-muted"><%= format_date fee.creation_time %></span>
      <div class="badge badge-secondary badge-pill d-block"><%= fee.fee_description %></div>
      PROCESSING
    </div>
    <div class="col-12 col-md-6  pb-2">
      <span class="text-muted text-sm">Item</span><br/>
      <span class="h6 font-weight-light"><%= fee.item_title %></span>
    </div>
    <div class="col-6 col-md-2 text-center">
      <span class="text-muted text-sm">Balance</span><br/>
      <span class="h4"><%= number_to_currency fee.balance %></span>
    </div>

    <div class="col-6 col-md-2 text-center">
      <span class="text-muted text-sm">Owner</span><br/>
      <%= fee.owner_description %>
    </div>
  </div>
  <% end %>
<% end %>

<% if Rails.env.development? %>
  <p class="mt-5">
    <%= link_to "Reload Fees", load_alma_fees_path, data: { disable_with: "Loading Fees, Please wait..." }%>
  </p>
  <p>Fees Loaded: <%= session[:alma_fees_loaded]  %></p>
<% end %>