config/routes.rb
Rails.application.routes.draw do





  # DEVISE setup
  devise_for :users

  ## FROM PRIMO Link
  get "/from_primo" => "from_primo#show"

  ## LOGIN VIA PASSPORT YORK
  get "/ppy_login" => "ppy_login#show"

  get "/home" => "home#show"

  ## LOAD FEES from ALMA
  get "alma/load_fees" => "alma/load_fees#index", as: :load_alma_fees

  ## REDIRECTOR to payment broker
  get "redirecting/to_payment_broker" => "redirectors/to_payment_broker#show", as: :redirect_to_payment_broker

  ## REDIRECTOR to alma fine payment
  get "redirecting/to_alma_fines" => "redirectors/to_alma_fines#show", as: :redirect_to_alma_fines

  ## POSTBACK From YPB
  resource :ypb_postback, only: :create, controller: "ypb_postback"

  ## PAYMENTS ##

  ## processing, creating transactions and records
  resources :process_payments, only: [:new, :create]

  ## details for completed transactions
  resources :transactions, only: [:index, :show]

  ## HOME ##
  root 'from_primo#show'

  ## REPORTS ##
  get "/reports" => "reports#index", as: :reports
  get "/reports/transaction/:id" => "reports/transactions#show", as: :report_transaction
  get "/reports/transaction/:id/logs" => "reports/transaction_logs#show", as: :report_transaction_log

  ## DUMMY ALMA API ##
  unless Rails.env.production?
    get "alma/dummy_api/:user_id/fees/" => "alma/dummy_fees_api#show", as: :alma_dummy_api_get_fees
    post "alma/dummy_api/:user_id/fees/:fee_id" => "alma/dummy_fees_api#update", as: :alma_dummy_api_fees
  end

end

app/controllers/reports/transaction_logs_controller.rb
class Reports::TransactionLogsController < AdminController

  def show
    @transaction = PaymentTransaction.find(params[:id])
    @logs = TransactionLog.where(transaction_id: params[:id]).order(:logged_at)
  end
end

app/controllers/reports/transactions_controller.rb
class Reports::TransactionsController < AdminController
  def show
    @transaction = PaymentTransaction.find(params[:id])
  end
end

app/controllers/reports_controller.rb
class ReportsController < AdminController

  def index
    @library = report_params[:library]
    @status = report_params[:status]
    @from = report_params[:from]
    @to = report_params[:to]

    @transactions = transactios_with_status @status

    @from_date = @from.blank? ? 1.month.ago : Date.parse(@from)
    @to_date = @to.blank? ? Date.today : Date.parse(@to)

    @transactions = @transactions.where('created_at BETWEEN ? AND ?', @from_date.beginning_of_day, @to_date.end_of_day)

    if !@library.blank?
      if @library == Alma::Fee::OWNER_OSGOODE
        @transactions = @transactions.where("library_id = ?" , Alma::Fee::OWNER_OSGOODE)
      elsif @library == "yorku"
        @transactions = @transactions.where.not("library_id = ?" , Alma::Fee::OWNER_OSGOODE)
      end
    end

    @grouped_transactions = @transactions.group_by(&:status)
  end

  private

  def report_params
    if params[:report] != nil
      params.require(:report).permit(:library, :status, :from, :to)
    else
      Hash.new
    end
  end

  def transactios_with_status(status)
    case status
    when PaymentTransaction::STATUS_PROCESSING
      PaymentTransaction.processing
    when PaymentTransaction::STATUS_PAID
      PaymentTransaction.paid
    when PaymentTransaction::STATUS_PAID_PARTIAL
      PaymentTransaction.paid_partial
    when PaymentTransaction::STATUS_REJECTED_BY_ALMA
      PaymentTransaction.rejected_by_alma
    when PaymentTransaction::STATUS_APPROVED
      PaymentTransaction.approved
    when PaymentTransaction::STATUS_DECLINED
      PaymentTransaction.declined
    when PaymentTransaction::STATUS_CANCELLED
      PaymentTransaction.cancelled
    else
      PaymentTransaction.all
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper

  def library_list
    [["All", "all"], ["York University Libraries", "yorku"], ["Osgoode Law Library", Alma::Fee::OWNER_OSGOODE]]
  end

  def library_name(id)
    if id == Alma::Fee::OWNER_OSGOODE
      "Osgoode Law Library"
    else
      "York University Libraries"
    end
  end
end

app/views/reports/index.html.erb
<% page_header "Reports", page_title: true %>

<%= simple_form_for :report, url: reports_path, method: :get do |f| %>
  <div class="row">
    <div class="col m3">
      <%= f.input :library, required: false,
        collection: library_list,
        selected: @library %>
    </div>
    <div class="col m3">
      <%= f.input :status,  required: false, allow_blank: true,
        collection: ["ALL"] + PaymentTransaction::STATUSES, selected: @status %>
    </div>
    <div class="col m2">
      <%= f.input :from, required: false, input_html: { value: @from } %>
    </div>
    <div class="col m2">
      <%= f.input :to, required: false, input_html: { value: @to } %>
    </div>
    <div class="col m2">
      <label class="string required d-block" for="report_to">&nbsp;</label>
      <%= f.submit "Generate", class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

<div class="d-none">
<%= @transactions.to_sql %>
</div>

<div class="border py-3 px-2 mt-4">

    <p>There were <%= @transactions.size %> payments
        <% if  !@from.blank? && !@to.blank? %>
        from <%= format_date Date.parse(@from) %> to <%= format_date Date.parse(@to) %>
        <% end %>
    </p>

  <% @grouped_transactions.each do |status, transactions| %>

    <% amount = transactions.select(&:total_amount_fees).inject(0){ |sum,x| sum + x.total_amount_fees.to_f} %>

    <p>Total <%= status %> transaction amount is: <strong><%= number_to_currency amount %></strong></p>
  <% end %>
</div>

<p class="mt-3">To view the receipt, click on the View Receipt Link</p>
<table class="table xtable-striped table-hover mt-3">
  <tr>
    <th>id</th>
    <th>Date</th>
    <th>Amount</th>
    <th>User ID</th>
    <th>Library</th>
    <th>Status</th>
    <th>YPB Order ID</th>
  </tr>
  <% @transactions.order(created_at: :desc).each do |t| %>
  <tr style="transform: rotate(0);">
    <td><%= link_to t.id, report_transaction_path(t.id), class: "stretched-link" %>
    <td><%= format_date t.created_at %></td>
    <td><%= number_to_currency (t.amount == nil ? t.total_amount_fees : t.amount) %></td>
    <td><%=  t.yorku_id %></td>
    <td><%= library_name t.library_id %></td>
    <td><%= t.status %></td>
    <td>
      <% if t.uid != nil %>
        <%= link_to "View Receipt", "#{Settings.ypb.receipt_page_url}?tokenid=#{t.uid}" %>
        <small class="d-block"><%= t.order_id %></small>
      <% else %>
        <%= t.order_id %>
      <% end %>

    </td>
  </tr>
  <% end %>
</table>
Total: <%= @transactions.size %>

<script type="text/javascript">
  var picker = new Lightpick({
    field: document.getElementById('report_from'),
    format: "YYYY-MM-DD",
    //minDate: new Date(),
    orientation: "bottom right",
  })

  var picker = new Lightpick({
    field: document.getElementById('report_to'),
    format: "YYYY-MM-DD",
    //minDate: new Date(),
    orientation: "bottom right",
  })

</script>